
import React from 'react';
import { FileText, Scale, Gavel } from 'lucide-react';

export const Terms: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto px-6 py-20">
      <div className="flex items-center gap-4 mb-12">
        <div className="w-12 h-12 bg-blue-500/10 rounded-2xl flex items-center justify-center border border-blue-500/20">
          <Scale className="text-blue-400 w-6 h-6" />
        </div>
        <div>
          <h1 className="text-4xl font-black font-satoshi tracking-tight">Terms of Service</h1>
          <p className="text-gray-500 font-medium">Standard License Agreement v2.1</p>
        </div>
      </div>

      <div className="glass p-10 rounded-[3rem] border-white/5 space-y-12 text-gray-400 leading-relaxed font-medium">
        <section>
          <h2 className="text-2xl font-black font-satoshi text-white mb-4">1. Acceptance of Terms</h2>
          <p>
            By accessing PromptGenieX, you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you may not access our platform.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-black font-satoshi text-white mb-4">2. Intellectual Property</h2>
          <p>
            You retain 100% ownership of the prompts generated through our platform. PromptGenieX claims no ownership over the output logic created by its engineering compilers. However, the PromptGenieX brand, its code, and its proprietary "logic mapping" algorithms are the exclusive property of PromptGenieX.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-black font-satoshi text-white mb-4">3. Prohibited Use</h2>
          <p>
            You may not use our platform to engineer prompts that:
          </p>
          <ul className="list-disc ml-6 mt-4 space-y-2">
            <li>Violate any local or international laws</li>
            <li>Promote hate speech or violence</li>
            <li>Attempt to bypass AI safety guardrails (Jailbreaking)</li>
            <li>Involve unauthorized data scraping</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-black font-satoshi text-white mb-4">4. Limitation of Liability</h2>
          <p>
            PromptGenieX provides tools for prompt optimization. We are not responsible for the outputs generated by third-party LLMs (ChatGPT, Claude, etc.) following the use of our prompts.
          </p>
        </section>
      </div>
    </div>
  );
};